<script src="<?= urlOf('assets/libs/popper/js/popper.min.js') ?>"></script>
<script src="<?= urlOf('assets/libs/jquery/js/jquery.min.js') ?>"></script>
<script src="<?= urlOf('assets/libs/bootstrap/js/bootstrap.min.js') ?>"></script>
<script src="<?= urlOf('assets/libs/slick/js/slick.min.js') ?>"></script>
<script src="<?= urlOf('assets/libs/countdown/js/jquery.countdown.min.js') ?>"></script>
<script src="<?= urlOf('assets/libs/mmenu/js/jquery.mmenu.all.min.js') ?>"></script>
<script src="<?= urlOf('assets/js/app.js') ?>"></script>
<script src="<?= urlOf('assets/libs/slider/js/tmpl.js') ?>"></script>
<script src="<?= urlOf('assets/libs/slider/js/jquery.dependClass-0.1.js') ?>"></script>
<script src="<?= urlOf('assets/libs/slider/js/draggable-0.1.js') ?>"></script>
<script src="<?= urlOf('assets/libs/slider/js/jquery.slider.js') ?>"></script>
<script src="<?= urlOf('assets/libs/elevatezoom/js/jquery.elevatezoom.js') ?>"></script>